### ISSUE TITLE
Reformuler le sous-titre

### ISSUE THREAD

**Issue by soizicpenicaud** [entrepreneur-interet-general/ma-semaine#11]
Au lieu de "Partage ta priorité, réussite et difficulté à l'équipe", je propose "Partagez votre priorité, réussite et difficulté à la promotion", pour que ce soit plus clair que l'on parle en tant qu'équipe défi à toute la promotion EIG 3.
Idem pour la phrase "Ces informations seront partagées par e-mail à toute l'équipe le vendredi à 15h." > remplacer "équipe" par "promotion" ?

**Comment by AntoineAugusti** [comment]
Hey @soizicpenicaud,

Thanks for your issue. You want to adapt the wording to the EIG program.

We're shooting for generic terms for now in order to build something easily reusable by other. We want to turn this little project into a successful open source one with reusers. Hence the generic terms for now!
