### ISSUE TITLE
Question sur le fonctionnement

### ISSUE THREAD

**Issue by milkosofi** [entrepreneur-interet-general/ma-semaine#25]
Est-ce à dessein que l'on ne précise pas le fait que les équipes sont les EIG sans leurs mentors ? 
J'imagine que cela permet à l'outil de rester assez général pour être utilisé par n'importe qui. Mais du coup c'est à garder à l'esprit dans l'explication que l'on fera de l'outil aux EIG.
Est-ce pour la même raison que l'on dit "votre projet" plutôt que "votre défi" dans le formulaire ?

**Comment by AntoineAugusti** [comment]
Hello,

This tool aims to be generic and not too tied to the EIG program to be easily reusable. That's why we didn't choose a wording specific to EIG but we'll tell this kind of things in our emails / Slack.

Related issue: https://github.com/entrepreneur-interet-general/ma-semaine/issues/11#issuecomment-469167482
