### ISSUE TITLE
Préciser les différentes façons dont seront visibles les réponses

### ISSUE THREAD

**Issue by milkosofi** [entrepreneur-interet-general/ma-semaine#26]
J'ai l'impression qu'il y a plusieurs degrés de visibilité et je me demande s'il ne faudrait pas les préciser : 
- chaque semaine, les réponses des uns et des autres sont rendues visibles à l'ensemble des équipes par l'envoi d'un mail. Cela permet de faire circuler l'information (et cela reprend la dernière partie de fonctionnement) ;
- chaque équipe peut accéder à ses comptes-rendus. Je ne suis pas sûre de comprendre comment : ont-elles accès à la base de données créée ? est-ce que les équipes ont accès à une base de données contenant toutes les réponses, y compris celles des autres équipes ? où vont-elles chercher le lien unique ?
- y a-t-il un dernier niveau de visibilité correspondant à Node-Core qui aurait accès à toutes les données ?

Ce sont des questions très naïves, mais j'espère pas inutiles...

**Comment by AntoineAugusti** [comment]
Hello,

You're asking about visibility of answers. Right now, it's not possible to see answers from previous weeks in the tool, but features are planned in #6, #19, #20 or #21.

What I think we will have:
- previous answers are available to everyone with access to the tool, so you can see the whole history for all projects
- projects and all have a unique secret URL that they can share to who they want, which only gives access to the history of a specific project
- since answers are shared by email to the whole team every week, this doesn't change the visibility of answers: everyone who receives the email already has the history

**Comment by jbledevehat** [comment]
Que penses-tu d'avoir une vision de tous les défis de la semaine passée dans report ? Et plus précisément par défaut sur https://ma-semaine.eig-forever.org/reports redirigé sur un onglet (1ère position) nommé "Semaine passée" avec l'URL https://ma-semaine.eig-forever.org/reports/S10 (comme cela nous conservons toutes les semaines passées)

**Comment by AntoineAugusti** [comment]
Hey, you're asking about accessing previous reports, not only by projects (seeing previous reports for a specific project) but also by week (seeing all reports for a specific week).

This is a planned feature. I've opened an issue in #36

**Comment by AntoineAugusti** [comment]
Closing as questions have been answered. Open a new issue if you have a question / want to request a feature.

Thanks
